Hafta06/Kutuphane/Kutuphane/Models/Kitap.cs
namespace Kutuphane.Models
{
    public class Kitap
    {
        public String ISSN { get; set; }
        public String Ad { get; set; } = String.Empty;
        public String Yazar{ get; set; } = String.Empty;
        public String ResimYolu { get; set; } = String.Empty;
        public double Fiyat { get; set; }
        public DateTime BasimTarihi { get; set; }
        public int SayfaSayisi { get; set; }

        public Kitap()
        {
            BasimTarihi=DateTime.Now;
        }
    }
}

Hafta06/Kutuphane/Kutuphane/Controllers/HomeController.cs
using Kutuphane.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Kutuphane.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

  
    }
}

Hafta06/Kutuphane/Kutuphane/Controllers/KitapController.cs
using Kutuphane.Models;
using Microsoft.AspNetCore.Mvc;

namespace Kutuphane.Controllers
{
    public class KitapController:Controller
    {
        public static List<Kitap> kitaplar = new();
        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Kitap k)
        {
            kitaplar.Add(k);
            return View("Liste", kitaplar);
        }

        public IActionResult Liste()
        {
            return View(kitaplar);
        }

    }
}

Hafta06/Kutuphane/Kutuphane/Views/Kitap/Ekle.cshtml
@model Kitap
<form asp-action="Ekle" asp-controller="Kitap" method="post">
    <div class="mb-3">
        <label class="form-label" asp-for="ISSN"></label>
        <input class="form-control" type="text" asp-for="ISSN" />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Ad"></label>
        <input class="form-control" type="text" asp-for="Ad" />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Yazar"></label>
        <input class="form-control" type="text" asp-for="Yazar" />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="ResimYolu"></label>
        <input class="form-control" type="text" asp-for="ResimYolu" />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Fiyat"></label>
        <input class="form-control" type="number" asp-for="Fiyat" />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="SayfaSayisi"></label>
        <input class="form-control" type="number" asp-for="SayfaSayisi" />
    </div>
    <div class="mb-3 btn-group">
        <button class="btn btn-primary" type="submit">Kaydet</button>
        <a class="btn btn-secondary" asp-action="Index" asp-controller="Home">İptal</a>
    </div>
</form>

Hafta06/Kutuphane/Kutuphane/Views/Kitap/Liste.cshtml
@model List<Kitap>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 mb-2">
            <div class="card" style="width: 18rem;">
                <img src="@item.ResimYolu" class="card-img-top" alt="@item.Ad">
                <div class="card-body">
                    <h5 class="card-title">@item.Ad</h5>
                    <p class="card-text">@item.Yazar</p>
                    <p class="card-text">@item.BasimTarihi</p>
                    <a href="#" class="btn btn-primary">@item.Fiyat</a>
                </div>
            </div>
        </div>
    }
</div>

Hafta06/Kutuphane/Kutuphane/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kutuphane</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kutuphane.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kutuphane</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Kutuphane - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>